# Generated by Django 5.0.3 on 2024-03-16 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_drink_food_product_productcategory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
