# Generated by Django 5.0.3 on 2024-03-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_drink_delete_food_remove_product_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='Categories',
        ),
    ]
