# Generated by Django 5.0.3 on 2024-03-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_productcategory_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
