# Generated by Django 5.0.3 on 2024-03-16 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_categories_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='nif',
            field=models.CharField(default='000000000', max_length=9, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(9)]),
        ),
    ]
